session_name: "archimedes"
matches:
  - name: ahahah
    filename: "archimedes.jpg"
    regex: "^[Аа](ха)+х?[ :!)]*$"
  - name: closing_parentheses
    filename: "fingernail.jpg"
    regex: "^\\)+$|^.*\\){2,}$"
