session_name: "archimedes"
matches:
  - name: ahahah_rus
    filename: "archimedes.jpg"
    regex: "^[Аа](ха)+х?[ :!)]*$"
  - name: ahahah_eng
    filename: "archimedes_eng.png"
    regex: "^[Aa](ha)+h?[ :!)]*$"
#  - name: closing_parentheses
#    filename: "fingernail.jpg"
#    regex: "^\\)+$|^.*\\){3,}$"
excludes:
  - ed00e1229475
